language: c
env:
  - WHYCONF=$PWD/.why3.conf

install:
  - ./scripts/install-dependencies.sh
  - export PATH=$PWD/z3-4.6.0-x64-ubuntu-14.04/bin:$PATH
  - export PATH=$PWD:$PATH
  - export PATH=$PWD/spark-discovery-gpl-2017-x86_64-linux-bin/bin:$PATH
  - $PWD/spark-discovery-gpl-2017-x86_64-linux-bin/libexec/spark/bin/why3config --detect-provers
  - cvc4 --version
  - cat /home/travis/.why3.conf
  - cp /home/travis/.why3.conf $PWD
  - echo $PATH
  - which cvc4
  - file cvc4
  - uname -a

script:
  - gnatprove -d -P minimal.gpr -f  --output-header --prover=altergo --timeout=1000 --steps=1000 --why3-conf=/home/travis/build/tofgarion/spark-by-example/.why3.conf nonlinear.adb
  - gnatprove -d -P minimal.gpr -f  --output-header --prover=cvc4 --timeout=1000 --steps=1000 --why3-conf=/home/travis/build/tofgarion/spark-by-example/.why3.conf nonlinear.adb
  - gnatprove -d -P minimal.gpr -f  --output-header --prover=z3 --timeout=1000 --steps=1000 --why3-conf=/home/travis/build/tofgarion/spark-by-example/.why3.conf nonlinear.adb
  # - cat $PWD/gnatprove/gnatprove.out
  # - cvc4 $PWD/gnatprove/find_p.adb_16_33_loop_invariant_preserv.smt2
