language: c

env:
  global:
    - GNAT_COMMUNITY_PATH=/opt/gnat-community-2018

cache:
  directories:
    - $GNAT_COMMUNITY_PATH

install:
  # check if GNAT Community is already in the cache, else install it
  - test -d $GNAT_COMMUNITY_PATH || ./scripts/install-dependencies.sh
  # export PATH
  - export PATH=/opt/gnat-community-2018/bin:$PATH

script:
  - gnatprove -P minimal.gpr --level=4 nonlinear.adb
