language: c

install:
  - ./scripts/install-dependencies.sh
  - sh ./gnat_community_install_script/install_package.sh ./gnat-community-2018 /opt/gnat-community-2018
  - export PATH=/opt/gnat-community-2018/bin:$PATH

script:
  - gnatprove -P minimal.gpr --level=4 nonlinear.adb
